# Error Handling

## Catching Errors

To catch an error in an observable stream, use the `catchPgError` RxJS operator:

```ts
export class UpdateUserEffects {
  private readonly usersApi = inject(UsersApi);
  private readonly alertService = inject(AlertService);

  public readonly updateUser(payload: UpdateUserRequest): Observable<User> {
    return this.usersApi.updateUser(payload).pipe(
        catchPgError((error) => {
            this.alertService.error(error.message);
        })
    );
  }
}
```

The `catchPgError` RxJS operator catches an error and wraps it into the `PGError` class. An instance of `PGError` will have the origin and message properties that might contain useful information about the original error that occurred.

Typically, the origin will be an `HttpErrorResponse`, but it might be other types of errors that occurred during the execution of a stream at runtime.

Handling API Errors
To handle an HTTP error response, simply use the handleError helper function inside of catchPgError:

```ts
export class UpdateUserEffects {
  private readonly usersApi = inject(UsersApi);
  private readonly alertService = inject(AlertService);

  public readonly updateUser(payload: UpdateUserRequest): Observable<User> {
    return this.usersApi.updateUser(payload).pipe(
        catchPgError((error) => {
            handleError(error);
        })
    );
  }
}
```

The `handleError` function accepts one required parameter, which is an instance of `PGError<HttpErrorResponse>`. Optionally, you can pass a map object as a second argument where the key is the `HttpReponseCode`, and the value will be an error handler function for that specific HTTP response code:

```ts
export class UpdateUserEffects {
  private readonly usersApi = inject(UsersApi);
  private readonly alertService = inject(AlertService);

  public readonly updateUser(payload: UpdateUserRequest): Observable<User> {
    return this.usersApi.updateUser(payload).pipe(
        catchPgError((error) => {

            const errorHandlingOverride = createHttpErrorHandlersMap({
              [HttpReponseCode.400]: (error: PGError<HttpErrorResponse>) => this.alertService.error(`A validation error occurred: ${error.message}`)
            });

            handleError(error, errorHandlingOverride);
        })
    );
  }
}
```

If a map with overrides is not provided, a default error handling behavior will be used.

## Error Handling in Effects Factory Functions

While using the effects helper functions `rxRequest`, `fetchEntities`, or `fetchData`, any API errors are automatically handled with the `catchPgError` RxJS operator under the hood. However, you can still override the behavior by defining the `errorHandler` property:

```ts
export class UpdateUserEffects {
    private readonly usersApi = inject(UsersApi);

  private readonly errorHandlingOverride = createHttpErrorHandlersMap({
    [HttpReponseCode.400]: (error: PGError<HttpErrorResponse>) => inject(AlertService).error(`A validation error occurred: ${error.message}`)
  });

  public readonly updateUser = rxRequest<UpdateUserRequest, void>({
    requestFn: (payload) => this.usersApi.updateUser(payload),
    errorHandler: this.errorHandlingOverride
  });
}
```

Note that the AlertService service is directly injected into the handler function:

```ts
  [HttpReponseCode.400]: (error: PGError<HttpErrorResponse>) => inject(UsersApi).error(`A validation error occurred: ${error.message}`);
```

It is possible because the `rxRequest`, `fetchEntities`, or `fetchData` helper functions run an error handler function within the injection context with the `runInInjectionContext` helper function.

Additionally, you can also pass the onError callback to have some additional side effects logic regardless of the error type and origin:

```ts
export class UpdateUserEffects {
  private readonly usersApi = inject(UsersApi);

  public readonly updateUser = rxRequest<UpdateUserRequest, void>({
    requestFn: (payload) => this.usersApi.updateUser(payload),
    onError: (error) => {
      console.log(error);
    },
  });
}
```

This is especially useful while debugging.

## Populating an Error to Store

In some cases, we would want to populate an occurred error in the store so it can be handled in the template as well.

Every time a store is created with either `callStateStore`, `simpleEntitiesStore`, `extendedEntitiesStore`, or `dataStore` factory function, the store feature for setting an error is added. This means that each store will have the error state and the setError method:

```ts
export class UpdateUserRepository {
  public readonly updateUserCallState = callStateStore();

  public readonly error = this.updateUserCallState.error; // Signal<PGError<HttpErrorResponse> | null>

  constructor() {
    this.updateUserCallState.setError(null); // (error: PGError<HttpErrorResponse> | null): void
  }
}
```

To make sure an error is populated to the store, pass the store parameter to either effects helper function:

```ts
  private readonly usersApi = inject(UsersApi);
  private readonly repository = inject(UpdateUserRepository);

  public readonly updateUser = rxRequest<PersonInfoForm['value'], void>({
    requestFn: (payload) => this.usersApi.updateUser(payload),
    store: this.repository.updateUserCallState,
  });
```

This will ensure that an occurred error is passed to the `setError` method and populated to the `updateUserCallState` store.
